---
- hosts: localhost
  vars:
    state: present
    s3_bucket: javahome-tf-test
    key: terraform.tfstate
    region: eu-west-1
    app_env: dev
  tasks:
    - name: Run terraform scripts
      terraform:
        project_path:"./"
        stage: "{{ state }}"
        backend_config:
          bucket: "{{ s3_bucket }}"
          key: "{{key}}"
          region: "{{region}}"
      variable_files: "{{app_env}}.tfvars"
      workspace: "{{ app_env }}"
